# Changes here will be overwritten by Copier
_commit: v0.1.8
_src_path: gh:edgarrmondragon/singer-tap-copier-template
author_email: edgarrmondragon@hey.com
author_fullname: Edgar Ramírez-Mondragón
author_username: edgarrmondragon
dependabot_update_time: '10:00'
dependabot_update_timezone: Etc/UTC
python_main_version: '3.12'
repository_name: tap-fedidb
repository_namespace: edgarrmondragon
repository_provider: github.com
repository_visibility: public
tap_auth_method: Custom or N/A
tap_id: tap-fedidb
tap_package_command_line_name: tap-fedidb
tap_package_distribution_name: tap-fedidb
tap_package_import_name: tap_fedidb
tap_source_description: Fediverse Network Statistics
tap_source_id: FediDB
tap_source_name: FediDB
tap_stream_type: REST
vscode_files: true
