name: Build and publish

on:
  push:

jobs:
  build:
    name: Build wheel and sdist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: hynek/build-and-inspect-python-package@v2

  publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/tap-fedidb
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist
    - uses: svenstaro/upload-release-action@v2
      with:
        file: dist/*.whl
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    - uses: pypa/gh-action-pypi-publish@v1.10.2
